- type: job
  id: CnsOfficer
  name: jon-name-cns-officer
  description: jon-description-cns-officer
  playTimeTracker: JobCnsOfficer
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hours
    - !type:TraitsRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        # - BrittleBoneDisease
        # Officer работает на NanoTrasen напрямую, доп. ограничение на работодателя не требуется
    - !type:OverallPlaytimeRequirement
      time: 7200
  weight: 20
  startingGear: CnsOfficerGear
  icon: "JobIconBlueshield"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  # - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Cargo
  - BlueshieldOfficer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, BluespaceLifelineImplant ] #Force the implant since its manual activation now
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: CPRTraining
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: CnsOfficerGear
  subGear:
  - CnsOfficerPlasmamanGear
  equipment:
    back: ClothingBackpackBlueshield
    jumpsuit: ClothingUniformJumpsuitBlueshieldOfficer
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesMedSec
    ears: ClothingHeadsetCorporations
    gloves: ClothingHandsGlovesCombat
    id: CnsOfficerPDA
    outerClothing: ClothingBlueshieldArmourVest
    #ears: ClothingHeadsetAltCommand
    #belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: WeaponDisabler
    #pocket2: DeathAcidifierImplanter
  storage:
    back:
    - MagazinePistol
    - MagazinePistol
    - Stunbaton
    - Handcuffs
    - Handcuffs

- type: startingGear
  id: CnsOfficerPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitBlueshield
    head: ClothingHeadEnvirohelmBlueshield
    gloves: ClothingHandsGlovesEnviroglovesBlack
