- type: job
  id: CnsRepresentative
  name: job-name-cns-representative
  description: job-description-cns-representative
  playTimeTracker: JobCnsRepresentative
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 54000 # 15 hours
    - !type:TraitsRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
    - !type:OverallPlaytimeRequirement
      time: 7200
  weight: 30
  startingGear: CnsRepresentativeGear
  icon: "JobIconNanotrasenRepresentative"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  # - Security
  # - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Lawyer
  - Cargo
  - Command
  - NanotrasenRepresentative
  - CentralCommand
  - BlueshieldOfficer
  - Lawyer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, BluespaceLifelineImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: CnsRepresentativeGear
  subGear:
  - CnsRepresentativePlasmamanGear
  equipment:
    back: ClothingBackpackCentcomm
    shoes: ClothingShoesColorBlack
    id: CnsRepresentativePDA
    jumpsuit: ClothingUniformJumpsuitNanotrasenRepresentative
    eyes: ClothingEyesGlassesCommand
    ears: ClothingHeadsetNtr
    # pocket1: UniqueNanorepLockerTeleporter
  storage:
    back:
    - RubberStampNanorep
    - Paper
    - Paper
    - BoxFolderGreen

- type: startingGear
  id: CnsRepresentativePlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitNanotrasenRepresentative
    head: ClothingHeadEnvirohelmNanotrasenRepresentative
    gloves: ClothingHandsGlovesEnviroglovesBlack
